// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6_YZm1Shi7-4G8m8vTLMfTsbxNVWICK0',
    appId: '1:719114093241:web:0e4692a02f7fc60dbb1168',
    messagingSenderId: '719114093241',
    projectId: 'foodgoo-52970',
    authDomain: 'foodgoo-52970.firebaseapp.com',
    storageBucket: 'foodgoo-52970.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP5EX70F7SSW3ssIE0GgfJuIuL-EjXFdU',
    appId: '1:719114093241:android:92d728160ffb3d64bb1168',
    messagingSenderId: '719114093241',
    projectId: 'foodgoo-52970',
    storageBucket: 'foodgoo-52970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClouztk9XFAUySoSBxIqoU42X-LY-aQAI',
    appId: '1:719114093241:ios:f2ba35d68b299bacbb1168',
    messagingSenderId: '719114093241',
    projectId: 'foodgoo-52970',
    storageBucket: 'foodgoo-52970.firebasestorage.app',
    iosBundleId: 'com.example.foodGo',
  );
}
